/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simple.gradle.java.app;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class AppTest {

    @Test
    void testGetSum() {
        int result = App.getSum(10, 12);
        assertEquals(22, result);
    }
}


